catalog:
  type: hive
  packaged: true
  readOnly: true
  properties:
    - key: type
      required: true
    - key: default-database
      required: false
    - key: property-version
      required: false
    - key: hive-conf-dir
      required: false
    - key: hive-version
      required: false
    - key: hadoop-conf-dir
      required: false
