---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          imagePullPolicy: IfNotPresent
          args: ["--log-bin",  "--binlog-format=ROW", "--server-id=1"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql
          emptyDir: {}    
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
